name: Release

on:
  push:
    branches: ['main']

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v3.1.0
        with:
          go-version-file: './go.mod'
      - run: go version

      - uses: securego/gosec@607d607b516bf301996678c68dc371a0dba9a938 #v2.11.0
        with:
          args: ./...

      - name: Install ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4
      - run: echo $(ko build  -t ${{ github.sha }} ./)

      - name: Sign the images with GitHub OIDC Token
        uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730 #v2.3.0

      - name: Signing Image
        run: cosign sign ${IMAGE}
        env:
          IMAGE: ${{ steps.install_ko.outputs.*}}
          COSIGN_EXPERIMENTAL: 1