name: Release

on:
  push:
    branches: ['main']

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v3.1.0
        with:
          go-version-file: './go.mod'
#      - run: go version
#
#      - uses: securego/gosec@607d607b516bf301996678c68dc371a0dba9a938 #v2.11.0
#        with:
#          args: ./...

      - name: Install ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

      - name: Sign the images with GitHub OIDC Token
        uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730 #v2.3.0

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance

      - name: Signing and build Image
        run: cosign sign $(ko build  -t ${{ github.sha }} . ) --attachment sbom
        env:
          COSIGN_EXPERIMENTAL: 1